name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # ou master selon votre workflow

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: npm install

      - name: Build the frontend project
        run: npm run build --prod  # Change si nécessaire

      - name: Build Docker image for frontend
        run: docker build -t djosh35/tickly-frontend:${{ github.sha }} -f ./.github/workflows/Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag djosh35/tickly-frontend:${{ github.sha }} djosh35/tickly-frontend:latest
          docker push djosh35/tickly-frontend:${{ github.sha }}
          docker push djosh35/tickly-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend  # Déploiement après construction du frontend

    steps:
      # Installer sshpass pour permettre l'utilisation de mots de passe avec SSH
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        run: |
          # Connexion au VPS en utilisant sshpass
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            # Pull the latest image for frontend
            docker pull djosh35/tickly-frontend:latest

            # Stop and remove any existing containers (si nécessaire)
            docker stop tickly-frontend || true
            docker rm tickly-frontend || true

            # Lancer le frontend
            docker run -d --name tickly-frontend -p 80:80 djosh35/tickly-frontend:latest
          EOF
