name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # Déclenche le workflow sur des pushes vers la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: |
          echo "Installing frontend dependencies..."
          npm install

      - name: Build the frontend project
        run: |
          echo "Building the frontend project..."
          npm run build --prod  # Change si nécessaire

      - name: Install sshpass
        run: |
          echo "Installing sshpass..."
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Transferring files to VPS..."
          # Supprimez le contenu existant dans le répertoire de Caddy
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "rm -rf /usr/share/caddy/*"

          # Transférez les nouveaux fichiers construits vers le VPS
          scp -r dist/tickly-front/browser/* root@$SERVER_IP:/usr/share/caddy/

          echo "Deployment completed!"

          # Redémarrez Caddy pour appliquer les modifications
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl restart caddy"

      - name: Check Caddy Status
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl status caddy"
