on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Retrieve the source code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Configure Node.js in the environment
        with:
          node-version: '22'  # Specify the Node.js version to use

      - name: Install frontend dependencies
        run: |
          echo "Installing frontend dependencies..."
          npm install  # Install the dependencies defined in package.json

      - name: Build the frontend project
        run: |
          echo "Building the frontend project..."
          npm run build --prod  # Compile the project in production mode

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Write the private key to the file
          chmod 600 ~/.ssh/id_rsa  # Set the correct permissions

      - name: Deploy to VPS
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Get the VPS IP from GitHub secrets
        run: |
          echo "Transferring files to VPS..."
          
          # Remove existing content in the Caddy directory
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP "rm -rf /usr/share/caddy/*" || { echo "Failed to connect to VPS"; exit 1; }

          # Transfer new built files to the VPS
          scp -r dist/tickly-front/browser/* root@$SERVER_IP:/usr/share/caddy/ || { echo "Failed to transfer files"; exit 1; }

          echo "Deployment completed! "

          # Restart Caddy to apply changes
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl restart caddy" || { echo "Failed to restart Caddy"; exit 1; }

      - name: Check Caddy Status
        run: |
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl status caddy" || { echo "Failed to check Caddy status"; exit 1; }
