on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Retrieve the source code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Configure Node.js in the environment
        with:
          node-version: '22'  # Specify the Node.js version to use

      - name: Install frontend dependencies
        run: |
          echo "Installing frontend dependencies..."
          npm install  # Install the dependencies defined in package.json

      - name: Build the frontend project
        run: |
          echo "Building the frontend project..."
          npm run build --prod  # Compile the project in production mode

      - name: Install sshpass
        run: |
          echo "Installing sshpass..."
          sudo apt-get update  # Update the package list
          sudo apt-get install -y sshpass  # Install sshpass for SSH connections with a password

      - name: Deploy to VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}  # Get the VPS password from GitHub secrets
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Get the VPS IP from GitHub secrets
        run: |
          echo "Transferring files to VPS..."
          
          # Debugging: Check if variables are set
          echo "VPS IP: $SERVER_IP"
          echo "VPS Password: [hidden]"

          # Remove existing content in the Caddy directory
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "rm -rf /usr/share/caddy/*" || { echo "Failed to connect to VPS"; exit 1; }

          # Transfer new built files to the VPS
          scp -r dist/tickly-front/browser/* root@$SERVER_IP:/usr/share/caddy/ || { echo "Failed to transfer files"; exit 1; }

          echo "Deployment completed!"

          # Restart Caddy to apply changes
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl restart caddy" || { echo "Failed to restart Caddy"; exit 1; }

      - name: Check Caddy Status
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl status caddy" || { echo "Failed to check Caddy status"; exit 1; }
